# Generated by Django 4.0.1 on 2022-03-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cl',
        ),
    ]
