# Generated by Django 4.0.1 on 2022-03-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='concern',
        ),
    ]
